### ISSUE TITLE
Doesn't work with Picasso 

### ISSUE THREAD

**Issue by samx786786** [virtualvivek/BlurShadowImageView#1]

**Comment by virtualvivek** [comment]
hi @samx786786 ,

 After a while i updated the project code and now it supports 
[Picasso](https://github.com/square/picasso) , [Glide](https://github.com/bumptech/glide) , and [Universal-Image-Loader](https://github.com/nostra13/Android-Universal-Image-Loader)  as well,
along with that **blurring algorithm** has been optimized too.



you can now use this new -version (1.2)

**implementation 'com.github.virtualvivek:BlurShadowImageView:1.2'**

**Comment by samx786786** [comment]
Sure thanks a lot
