### ISSUE TITLE
Feature request: Image scaling

### ISSUE THREAD

**Issue by rama-2402** [virtualvivek/BlurShadowImageView#2]
Hi, It would be great if there is image scaling (centerCrop, fitXY etc) available. awesome library btw. easy to implement and looks gorgeous :)

**Comment by virtualvivek** [comment]
Hey @rama-2402 ,
Yes its great to add prop for controlling image scaling, thank you for your suggestion 😊 I start work on it and add it as soon as possible , you will see it in the next release i.e. `(-v2.1)`

**Comment by rama-2402** [comment]
> Hey @virtualvivek  ,
Thanks for the implementation. Looking forward to the next update :)

**Comment by virtualvivek** [comment]
Hey @rama-2402 ,
I have updated library to <b>-v2.1</b>
You can now implement `Image Scaling` using <b>android:scaleType:"string"</b> prop.
It supports all type of ImageView Scaling includes:
"center"
"centerCrop"
"fitEnd"
"fitCenter"
"fitXY"
"centerInside"
"fitStart"
"matrix"

**Comment by rama-2402** [comment]
Thank you @virtualvivek  :)
